### ISSUE TITLE
Setup file not found

### ISSUE THREAD

**Issue by tk5011** [iRayanKhan/homebridge-roomba2#3]
I conducted the steps from the setup procedure as documented here:
https://github.com/iRayanKhan/homebridge-roomba2/blob/master/README.md

However there were quite some warnings in the log (the plugin was installed however and is visible in the homebridge UI).

```
pi@raspberrypi4:/ $ sudo npm i -g homebridge-roomba2
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
+ homebridge-roomba2@1.0.0
updated 1 package in 22.896s
pi@raspberrypi4:/ $ cd /usr/local/lib/node_modules/
-bash: cd: /usr/local/lib/node_modules/: Datei oder Verzeichnis nicht gefunden
```

The folder with the `getrobotpwd` is not available. (I have a pi). Where can I find the file?

**Comment by iRayanKhan** [comment]
Does the error translate to path not found?

**Comment by tk5011** [comment]
Yes, that is correct. Folder not found. There is nothing like node or similar in the folder `/usr/local/lib/`. Only python stuff...
Thanks

**Comment by iRayanKhan** [comment]
Do you know where your plug-ins are installed?

**Comment by tk5011** [comment]
Unfortunately now. homebridge directory seems to be in `/var/lib/homebridge`, but I was not able to spot the corresponding folder yet. I installed the plugin via the homepage via the plugins-tab. Also the log from homebridge does not point to any folder.

Appreciate your help!

**Comment by tk5011** [comment]
I found the folder in the meantime in `/usr/lib/node_modules/homebridge-roomba2`.
Executing the script getrobotpwd also worked and I got robot data `blid` etc. (after pressing the home button of the roomba until the sound comes up). However it is not clear to me which value to insert as `Robot Password` in the config.
There is no such value in the `robot data` from the script (only ver, hostname, robotname, ip, mac, sw, sku, nc, proto, cap..., blid)

The robot data remains on the screen and an additional enter the following error message shows up:

`Robot Data: 
{
  ver: '3',
  hostname: 'Roomba-XXXXXXXXXXXXXXXXXXX',
  robotname: 'Rob',
  ip: '192.168.XXX.XX',
  mac: 'XXXXXXXXX',
  sw: 'v2.4.8-44',
  sku: 'R96----',
  nc: 0,
  proto: 'mqtt',
  cap: {
    pose: 1,
    ota: 2,
    multiPass: 2,
    pp: 1,
    binFullDetect: 1,
    langOta: 1,
    maps: 1,
    edge: 1,
    eco: 1,
    svcConf: 1
  },
  blid: 'XXXXXXXXXXXXX'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.178.30:8883
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.XXX.XX',
  port: 8883
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! homebridge-roomba2@1.0.0 getrobotpwd: `cd node_modules/dorita980 && npm install && node ./bin/getpassword.js "192.168.XXX.XX"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the homebridge-roomba2@1.0.0 getrobotpwd script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-29T06_49_27_034Z-debug.log
pi@raspberrypi4:/usr/lib/node_modules/homebridge-roomba2 $ 
`

**Comment by iRayanKhan** [comment]
Try running the command with sudo.

**Comment by iRayanKhan** [comment]
Please refer to #8

**Comment by whreams** [comment]
+1 to this issue.  Found this error upon trying to obtain the pw.

events.js:287
      throw er; // Unhandled 'error' event
      ^

I also get the blind, just not the password.

**Comment by karlvr** [comment]
@tk5011 did you provide the IP address as 192.168.XXX.XX? You need to discover the actual IP address of your Roomba.
